version: '3'
services:
  server:
    image : "skillbillsrl/hackaton-20210528-api:${TAG}"
    ports:
      - "3000:3000"
    volumes: 
      - /var/log/server:/var/log/server
  front-end:
    image : "skillbillsrl/hackaton-20210528-frontend:${TAG}"
    ports:
      - "127.0.0.1:8080:80"
    volumes: 
      - /config/config-front-end.json:/config.json